[features]
seeds = false
skip-lint = false
[programs.localnet]
hello_anchor = "Cb8qWGvvf8WVtwkUXwmmcYKcQH4fpr6D4oD56h58ttpA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/simon/key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
